name: maincopiertwo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 1.15.17

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 3.0.0
  equatable: 1.1.1
  flutter_bloc: 3.2.0
  flutter_launcher_icons: 0.7.4
  intl: 0.16.1
  lumberdash: 2.1.1
  print_lumberdash: 2.1.0
  user_repository:
    path: ./repositories/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 4.0.0
  intl_translation: 0.17.9
  mockito: 4.1.1
  nitpicky:
    git:
      url: https://github.com/VGVentures/nitpicky
      ref: 1.0.2

flutter:
  uses-material-design: true
